#!/bin/bash

echo -en "\n[//]: # (This is an autogenerated file using $0 script. Do not edit manually.)\n\n"
while read file; do
	url="${file// /%20}"
	echo -en "## [$file]($url)\n"
	awk '/^## Rule[1-9]/,/^###/ { print }' "$file" | grep -v "##";
done < <(find . -name "README.md" -exec grep "Rule1" {} \; -print | grep -v "^##") | dos2unix
